# Generated by Django 6.0.3 on 2026-05-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_stock_quantity_to_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
