# Generated by Django 6.0.3 on 2026-05-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_watch_description_watch_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='image_url',
        ),
        migrations.AddField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watches/'),
        ),
    ]
