# Generated by Django 6.0.3 on 2026-05-04 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_watch_image_url_watch_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('market_price_eur', models.CharField(blank=True, max_length=50, null=True)),
                ('movement', models.CharField(blank=True, max_length=255, null=True)),
                ('family_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year_produced', models.CharField(blank=True, max_length=100, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('limited', models.CharField(blank=True, max_length=10, null=True)),
                ('external_image', models.CharField(blank=True, max_length=500, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('watch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='api.watch')),
            ],
        ),
    ]
